blank_issues_enabled: false

contact_links:
  - name: MetaTube GitHub Wiki
    url: https://metatube-community.github.io/wiki/
    about: Please see the wiki for configuration and examples
  - name: MetaTube GitHub Discussions
    url: https://github.com/metatube-community/MetaTube.bundle/discussions
    about: Ask questions and get help on GitHub Discussions
